### PR TITLE
Manage a transaction to disable the read only flag in loadAges. #163

### PR DESCRIPTION
**Pull request by kazuki43zoo**
`@Transactional` does not work on `@PostConstruct`'s method. 

e,g)
```java
@Transactional
@PostConstruct
public void loadAges() {
    // ...
}     
```

Therefore, i manage a transaction manually using the `TransactionTemplate`.

Please review #163 .

### CODE REVIEW

**Comment by making** [comment]
What happens unless `TransactionTemplate`? and should this method be transactional?

**Comment by btshimizukza** [comment]
If execution without transactional, #163 can not resolved at the `loadAges`(Occur a `SQLException` when call the `AgeRepository#findOne`).

I tried following methods:

* Add the `@Transactional` at `loadAges` -> does not work

 ```java
 @Transactional // ### Added, but does not applied the TransactionInterceptor(AOP)
 @PostConstruct
 public void loadAges() {
     // ...
 }   
 ```

* Manage a transaction(non `readOnly` transaction) using `TransactionTemplate` (method of pull-request)

* Delegate the `SharedService`(create `AgeSharedService`)

 ```java
 @Service
 public AgeSharedServiceImpl implements AgeSharedService {
     @Inject
     Agerepository ageRepository;

     @Transactional // ### Non readOnly = true
     public Age findOne(String id){
         return ageRepository.findOne(id);
     }
 }
 ```

 ```java
 @PostConstruct
 public void loadAges() {
      this.childAge = ageSharedService.findOne("1");
      this.adultAge = ageSharedService.findOne("0");     
 }   
 ```

* Override the readOnly flag of `JpaRepository` (Repository of Spring Data JPA)

 ```java
 public interface AgeRepository extends JpaRepository<Age, String> {
     @Transactional // ### Non readOnly = true
     Age findOne(String id);
 }
 ```

**Comment by making** [comment]
Please add a comment like

``` java
// use TransactionTemplate to avoid SQLException which tells set-readonly is not allowed
// see https://github.com/terasolunaorg/terasoluna-tourreservation/issues/163
transactionTemplate.execute(new TransactionCallbackWithoutResult() {
    @Override
    protected void doInTransactionWithoutResult(TransactionStatus status) {
        childAge = ageRepository.findOne("1");
        adultAge = ageRepository.findOne("0");
    }
});
```

**Comment by btshimizukza** [comment]
add a comment.
Please review again.

**Pull request merged**
