### PR TITLE
replace config

### PR DESCRIPTION
**Pull request by btishiwatasns**
#325
use replace config tool

### CODE REVIEW

**Comment by making** [comment]
Also add `context.xml` including default values so that users who don't have the tool can deploy.

**Comment by btshimizukza** [comment]
Please create a new issue for adding `context.xml` created by replace tool.

**Comment by btshimizukza** [comment]
Please backport to 5.0.x and 1.0.x.

**Comment by btshimizukza** [comment]
@btishiwatasns Please reflect to [mybatis repository](https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3).

**Pull request merged**
